version: '3.8'
services:
  db:
    image: postgres:13.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5431:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 30s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - my_network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DEBUG: 1
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      PORT: 8000
      GUNICORN_WORKERS: 4
    networks:
      - my_network

volumes:
  pgdata:
  static_volume:


networks:
  my_network:
